# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestCreateCommunity():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_create_community(self):
        self.driver.get("http://localhost:5000/login")
        time.sleep(2)
        self.driver.set_window_size(912, 1011)
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        time.sleep(2)
        self.driver.get("http://localhost:5000/community/create")
        time.sleep(2)
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys("Test Community")
        self.driver.find_element(By.ID, "description").click()
        self.driver.find_element(By.ID, "description").send_keys("This is a test community.")
        self.driver.find_element(By.ID, "submit").click()
        time.sleep(2)

    def test_join_community(self):
        self.driver.get("http://localhost:5000/login")
        time.sleep(2)
        self.driver.set_window_size(912, 1011)
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        time.sleep(2)
        self.driver.get("http://localhost:5000/community")
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//button[contains(text(), 'Join')]").click()
        time.sleep(2)

    def test_leave_community(self):
        self.driver.get("http://localhost:5000/login")
        time.sleep(2)
        self.driver.set_window_size(912, 1011)
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        time.sleep(2)
        self.driver.get("http://localhost:5000/community")
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//button[contains(text(), 'Leave')]").click()
        time.sleep(2)
