"""Add communities tables

Revision ID: 005
Revises: 004
Create Date: 2024-12-14 14:39:39.967209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.alter_column(
            'name',
            existing_type=mysql.VARCHAR(length=100),
            type_=sa.String(length=120),
            existing_nullable=False)
        batch_op.alter_column(
            'description',
            existing_type=mysql.TEXT(),
            nullable=False)
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'community', ['community_id'], ['id'])
        batch_op.drop_column('publico')

    with op.batch_alter_table('deposition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=False))
        batch_op.drop_column('dep_metadata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposition', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'dep_metadata',
            mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
            nullable=False))
        batch_op.drop_column('meta_data')

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publico', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('community_id')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column(
            'description',
            existing_type=mysql.TEXT(),
            nullable=True)
        batch_op.alter_column(
            'name',
            existing_type=sa.String(length=120),
            type_=mysql.VARCHAR(length=100),
            existing_nullable=False)
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
