"""empty message

Revision ID: 240b4b000b47
Revises: f382f00caabc
Create Date: 2024-12-12 22:24:16.994982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '240b4b000b47'
down_revision = 'f382f00caabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_members')
    op.drop_table('community')
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('publico')

    with op.batch_alter_table('deposition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=False))
        batch_op.drop_column('dep_metadata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dep_metadata', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False))
        batch_op.drop_column('meta_data')

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publico', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    op.create_table('community',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('community_members',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('community_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], name='community_members_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='community_members_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'community_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
