"""Initial migration with is_confirmed field

Revision ID: 5c3416ecc651
Revises: d35838031251
Create Date: 2024-11-11 20:13:51.015803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3416ecc651'
down_revision = 'd35838031251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_email_confirmed')

    # ### end Alembic commands ###
